--------------------------------------------------------------------------
--									--
--									--
--				ZizoEXT.lua				--
--									--
--									--
--------------------------------------------------------------------------
print( "Loading ZizoEXT.lua" )

function z_f1()
	
	Talk(1,"Hello I am the Normal Gem Seller")
	Text(1,"I want to check your gems!", BuyPage)

	InitTrade()
	Weapon(	5750	)
	Weapon(	5751	)
	Weapon(	5752	)
	Weapon(	5775	)
	Weapon(	881	)
	Weapon(	884	)
	Weapon(	887	)
	Weapon(	860	)
	Weapon(	861	)
	Weapon(	862	)
	Weapon(	863	)
	Weapon(	1012	)
end

function z_f2()
	
	Talk(1,"Hello I am the Instant Level Giver")
	Text(1,"I want to get lv75 please!", BuyPage)

	InitTrade()
	Weapon(	7304	)
	
end

function ItemUse_Lv75Lvl ( role , Item )
	local Cha_Boat = 0
	local charLv=Lv ( role )
	local dif_exp_five = DEXP[75]
	local cha_skill_num = GetChaAttr( role, ATTR_TP )
	cha_skill_num = cha_skill_num + 150

	Cha_Boat = GetCtrlBoat ( role )
	if Cha_Boat ~=  nil then
		SystemNotice( role , "Cannot use while sailing" )
		UseItemFailed ( role )
		return
	end
	if charLv < 2 then
		SetChaAttrI( role , ATTR_CEXP , dif_exp_five )
		SetChaAttr(role, ATTR_TP, cha_skill_num )
			else
		SystemNotice( role , "Level too high to use" )
		UseItemFailed ( role )
		return
	
	end
end

--Class Changer
function z_f3 ()

	Talk( 1, "Job Advancer: Hi! I am Job Changer, Job Advancer. Let's see what i can do for you." )
	Text( 1, "First Job Promotion", JumpPage, 2)
	Text( 1, "Second Job Promotion", JumpPage, 3)
	Text( 1, "Nothing...",  CloseTalk)


	Talk( 2, "Job Advancer: Choose one of the following First Job Promotions." )
	Text( 2, "Swordsman", JumpPage, 4 )
	Text( 2, "Hunter", JumpPage, 5 )
	Text( 2, "Herbalist", JumpPage, 6 )
	Text( 2, "Explorer", JumpPage, 7 )
	Text( 2, "White Knight", JumpPage, 17 )	
	Text( 2, "Go back", JumpPage, 1 )

	Talk( 3, "Job Advancer: Choose one of the following Second Job Promotions." )
	Text( 3, "Crusader Promotion", JumpPage, 8 )
	Text( 3, "Champion Promotion", JumpPage, 9 )
	Text( 3, "Sharpshooter Promotion", JumpPage, 10 )
	Text( 3, "Cleric Promotion", JumpPage, 11 )
	Text( 3, "Seal Master Promotion", JumpPage, 12 )
	Text( 3, "Voyager Promotion", JumpPage, 13 )
	Text( 3, "Go Back", JumpPage, 1 )

	
	Talk( 17, "You have decided to become a White Knight please confirm." )
	InitTrigger()
	TriggerCondition( 1, LvCheck, ">", 8 )
	TriggerCondition( 1, IsCategory, 1 )
	TriggerCondition( 1, PfEqual, 0 )
	TriggerAction( 1, SetProfession, 10 )
	TriggerAction( 1, GiveItem, 3718, 1, 4)	
	TriggerAction( 1, JumpPage, 14 )
	TriggerCondition( 2, LvCheck, ">", 8 )
	TriggerCondition( 2, IsCategory, 3 )
	TriggerCondition( 2, PfEqual, 0 )
	TriggerAction( 2, JumpPage, 14 )
	TriggerCondition( 3, LvCheck, ">", 8 )
	TriggerCondition( 3, IsCategory, 2 )
	TriggerCondition( 3, PfEqual, 0 )
	TriggerAction( 3, JumpPage, 14 )
	TriggerFailure( 3, JumpPage, 15 )	
	
	Text( 17, "Agree to serve as a White Knight", MultiTrigger, GetMultiTrigger(), 3)
	Text( 17, "I want another Job", JumpPage, 2 )
	
	
	Talk( 4, "Job Advancer: After all, you want to become a Swordsman, very well. I am going to need 1000g and you need to be lv 9 or higher." )
	InitTrigger()
	TriggerCondition( 1, LvCheck, ">", 8 )
	TriggerCondition( 1, IsCategory, 1 )
	TriggerCondition( 1, PfEqual, 0 )
	TriggerAction( 1, SetProfession, 1 )
	TriggerAction( 1, JumpPage, 14 )
	TriggerCondition( 2, LvCheck, ">", 8 )
	TriggerCondition( 2, IsCategory, 3 )
	TriggerCondition( 2, PfEqual, 0 )
	TriggerAction( 2, SetProfession, 1 )
	TriggerAction( 2, JumpPage, 14 )
	TriggerCondition( 3, LvCheck, ">", 8 )
	TriggerCondition( 3, IsCategory, 2 )
	TriggerCondition( 3, PfEqual, 0 )
	TriggerAction( 3, SetProfession, 1 )
	TriggerAction( 3, JumpPage, 14 )
	TriggerFailure( 3, JumpPage, 15 )	
	
	Text( 4, "Become Swordman", MultiTrigger, GetMultiTrigger(), 3)
	Text( 4, "I want another Job", JumpPage, 2 )

	Talk( 5, "Job Advancer: After all, you want to become a Hunter, very well. I am going to need 1000g and you need to be lv 9 or higher." )
	InitTrigger()
	TriggerCondition( 1, LvCheck, ">", 8 )
	TriggerCondition( 1, IsCategory, 1 )
	TriggerCondition( 1, PfEqual, 0 )
	TriggerAction( 1, SetProfession, 2 )
	TriggerAction( 1, JumpPage, 14 )
	TriggerCondition( 2, LvCheck, ">", 8 )
	TriggerCondition( 2, IsCategory, 3 )
	TriggerCondition( 2, PfEqual, 0 )
	TriggerAction( 2, SetProfession, 2 )
	TriggerAction( 2, JumpPage, 14 )
	TriggerFailure( 2, JumpPage, 15 )
	Text( 5, "Become Hunter", MultiTrigger, GetMultiTrigger(), 2)
	Text( 5, "I want another Job", JumpPage, 2 )


	Talk( 6, "Job Advancer: After all, you want to become a Herbalist, very well. I am going to need 1000g and you need to be lv 9 or higher." )
	InitTrigger()
	TriggerCondition( 1, LvCheck, ">", 8 )
	TriggerCondition( 1, IsCategory, 3 )
	TriggerCondition( 1, PfEqual, 0 )
	TriggerAction( 1, SetProfession, 5 )
	TriggerAction( 1, JumpPage, 14 )
	TriggerCondition( 2, LvCheck, ">", 8 )
	TriggerCondition( 2, IsCategory, 4 )
	TriggerCondition( 2, PfEqual, 0 )
	TriggerAction( 2, SetProfession, 5 )
	TriggerAction( 2, JumpPage, 14 )
	TriggerFailure( 2, JumpPage, 15 )
	Text( 6, "Become Herbalist", MultiTrigger, GetMultiTrigger(), 2)
	Text( 6, "I want another Job", JumpPage, 2 )

	Talk( 7, "Job Advancer: After all, you want to become a Explorer, very well. I am going to need 1000g and you need to be lv 9 or higher." )
	InitTrigger()
	TriggerCondition( 1, LvCheck, ">", 8 )
	TriggerCondition( 1, IsCategory, 1 )
	TriggerCondition( 1, PfEqual, 0 )
	TriggerAction( 1, SetProfession, 4 )
	TriggerAction( 1, JumpPage, 14 )
	TriggerCondition( 2, LvCheck, ">", 8 )
	TriggerCondition( 2, IsCategory, 3 )
	TriggerCondition( 2, PfEqual, 0 )
	TriggerAction( 2, SetProfession, 4 )
	TriggerAction( 2, JumpPage, 14 )
	TriggerCondition( 3, LvCheck, ">", 8 )
	TriggerCondition( 3, IsCategory, 4 )
	TriggerCondition( 3, PfEqual, 0 )
	TriggerAction( 3, SetProfession, 4 )
	TriggerAction( 3, JumpPage, 14 )
	TriggerFailure( 3, JumpPage, 15 )
	Text( 7, "Become Explorer", MultiTrigger, GetMultiTrigger(), 3)
	Text( 7, "I want another Job", JumpPage, 2 )


	Talk( 8, "Job Advancer: After all, you want to become a Crusader, very well. I am going to need 50000g and you need to be lv 40 or higher." )
	InitTrigger()
	TriggerCondition( 1, LvCheck, ">", 39 )
	TriggerCondition( 1, IsCategory, 1 )
	TriggerCondition( 1, PfEqual, 1 )
	TriggerAction( 1, SetProfession, 9 )
	TriggerAction( 1, GiveItem, 7590, 2, 4)	
	TriggerAction( 1, JumpPage, 14 )
	TriggerCondition( 2, LvCheck, ">", 39 )
	TriggerCondition( 2, IsCategory, 3 )
	TriggerCondition( 2, PfEqual, 1 )
	TriggerAction( 2, SetProfession, 9 )
	TriggerAction(2, GiveItem, 7590, 2, 4)	
	TriggerAction( 2, JumpPage, 14 )
	TriggerFailure( 2, JumpPage, 15 )
	Text( 8, "Become Crusader", MultiTrigger, GetMultiTrigger(), 2)
	Text( 8, "I want another Job", JumpPage, 2 )

	Talk( 9, "Job Advancer: After all, you want to become a Champion, very well. I am going to need 50000g and you need to be lv 40 or higher." )
	InitTrigger()
	TriggerCondition( 1, LvCheck, ">", 39 )
	TriggerCondition( 1, IsCategory, 2 )
	TriggerCondition( 1, PfEqual, 1 )
	TriggerAction( 1, SetProfession, 8 )
	TriggerAction( 1, GiveItem, 7590, 2, 4)	
	TriggerAction( 1, JumpPage, 14 )
	TriggerFailure( 1, JumpPage, 15 )
	Text( 9, "Become Champion", MultiTrigger, GetMultiTrigger(), 1)
	Text( 9, "I want another Job", JumpPage, 2 )

	Talk( 10, "Job Advancer: After all, you want to become a Sharpshooter, very well. I am going to need 50000g and you need to be lv 40 or higher." )
	InitTrigger()
	TriggerCondition( 1, LvCheck, ">", 39 )
	TriggerCondition( 1, IsCategory, 1 )
	TriggerCondition( 1, PfEqual, 2 )
	TriggerAction( 1, SetProfession, 12 )
	TriggerAction( 1, GiveItem, 7590, 2, 4)	
	TriggerAction( 1, JumpPage, 14 )
	TriggerCondition( 2, LvCheck, ">", 39 )
	TriggerCondition( 2, IsCategory, 3 )
	TriggerCondition( 2, PfEqual, 2 )
	TriggerAction( 2, SetProfession, 12 )
	TriggerAction( 2, GiveItem, 7590, 2, 4)	
	TriggerAction( 2, JumpPage, 14 )
	TriggerFailure( 2, JumpPage, 15 )
	Text( 10, "Become Sharpshooter", MultiTrigger, GetMultiTrigger(), 2)
	Text( 10, "I want another Job", JumpPage, 2 )

	Talk( 11, "Job Advancer: After all, you want to become a Cleric, very well. I am going to need 50000g and you need to be lv 40 or higher." )
	InitTrigger()
	TriggerCondition( 1, LvCheck, ">", 39 )
	TriggerCondition( 1, IsCategory, 3 )
	TriggerCondition( 1, PfEqual, 5 )
	TriggerAction( 1, SetProfession, 13 )
	TriggerAction( 1, GiveItem, 7590, 2, 4)
	TriggerAction( 1, GiveItem, 3300, 1, 4)
	TriggerAction( 1, GiveItem, 3719, 1, 4)		
	TriggerAction( 1, JumpPage, 14 )
	TriggerCondition( 2, LvCheck, ">", 39 )
	TriggerCondition( 2, IsCategory, 4 )
	TriggerCondition( 2, PfEqual, 5 )
	TriggerAction( 2, SetProfession, 13 )
	TriggerAction( 2, GiveItem, 7590, 2, 4)
	TriggerAction( 2, GiveItem, 3300, 1, 4)
	TriggerAction( 2, GiveItem, 3719, 1, 4)		
	TriggerAction( 2, JumpPage, 14 )
	TriggerFailure( 2, JumpPage, 15 )
	Text( 11, "Become Cleric", MultiTrigger, GetMultiTrigger(), 2)
	Text( 11, "I want another Job", JumpPage, 2 )

	Talk( 12, "Job Advancer: After all, you want to become a Seal Master, very well. I am going to need 50000g and you need to be lv 40 or higher." )
	InitTrigger()
	TriggerCondition( 1, LvCheck, ">", 39 )
	TriggerCondition( 1, IsCategory, 3 )
	TriggerCondition( 1, PfEqual, 5 )
	TriggerAction( 1, SetProfession, 14 )
	TriggerAction( 1, GiveItem, 7590, 2, 4)
	TriggerAction( 1, GiveItem, 3300, 1, 4)
	TriggerAction( 1, GiveItem, 3719, 1, 4)		
	TriggerAction( 1, JumpPage, 14 )
	TriggerCondition( 2, LvCheck, ">", 39 )
	TriggerCondition( 2, IsCategory, 4 )
	TriggerCondition( 2, PfEqual, 5 )
	TriggerAction( 2, SetProfession, 14 )
	TriggerAction( 2, GiveItem, 7590, 2, 4)
	TriggerAction( 2, GiveItem, 3300, 1, 4)
	TriggerAction( 2, GiveItem, 3719, 1, 4)		
	TriggerAction( 2, JumpPage, 14 )
	TriggerFailure( 2, JumpPage, 15 )
	Text( 12, "Become Seal Master", MultiTrigger, GetMultiTrigger(), 2)
	Text( 12, "I want another Job", JumpPage, 2 )

	Talk( 13, "Job Advancer: After all, you want to become a Voyager, very well. I am going to need 50000g and you need to be lv 40 or higher." )
	InitTrigger()
	TriggerCondition( 1, LvCheck, ">", 39 )
	TriggerCondition( 1, IsCategory, 1 )
	TriggerCondition( 1, PfEqual, 4 )
	TriggerAction( 1, SetProfession, 16 )
	TriggerAction( 1, GiveItem, 7590, 2, 4)
	TriggerAction( 1, GiveItem, 3300, 1, 4)
	TriggerAction( 1, GiveItem, 3719, 1, 4)		
	TriggerAction( 1, JumpPage, 14 )
	TriggerCondition( 2, LvCheck, ">", 39 )
	TriggerCondition( 2, IsCategory, 3 )
	TriggerCondition( 2, PfEqual, 4 )
	TriggerAction( 2, SetProfession, 16 )
	TriggerAction( 2, GiveItem, 7590, 2, 4)
	TriggerAction( 2, GiveItem, 3300, 1, 4)
	TriggerAction( 2, GiveItem, 3719, 1, 4)		
	TriggerAction( 2, JumpPage, 14 )
	TriggerCondition( 3, LvCheck, ">", 39 )
	TriggerCondition( 3, IsCategory, 4 )
	TriggerCondition( 3, PfEqual, 4 )
	TriggerAction( 3, SetProfession, 16 )
	TriggerAction( 3, GiveItem, 7590, 2, 4)
	TriggerAction( 3, GiveItem, 3300, 1, 4)
	TriggerAction( 3, GiveItem, 3719, 1, 4)		
	TriggerAction( 3, JumpPage, 14 )
	TriggerFailure( 3, JumpPage, 15 )
	Text( 13, "Become Voyager", MultiTrigger, GetMultiTrigger(), 3)
	Text( 13, "I want another Job", JumpPage, 2 )

	Talk( 14, "Job Advancer: I will be always here, come back whenever you want to.")
	Text( 14, "Thanks",  CloseTalk)

	Talk( 15, "Job Advancer:Something is not right, make sure you got all necessary requeriments!")
	Text( 15, "I understand",  CloseTalk)

end

